use std::io::Write;

struct Guest {
    entry_gpa: usize,
    harts_cap: usize,
}
impl Guest {
    fn new(entry_gpa: usize, harts_cap: usize) -> Self {
        Self {
            entry_gpa,
            harts_cap,
        }
    }
}

fn main() {
    println!("cargo:rerun-if-changed=config.dts");

    let out_dir = std::env::var("OUT_DIR").unwrap();

    // Compile Device Tree file
    let dtb_output_path = std::path::PathBuf::from(&out_dir).join("config.dtb");
    let dts_source_path = "config.dts";

    let dtc_output = std::process::Command::new("dtc")
        .arg("-I")
        .arg("dts")
        .arg("-O")
        .arg("dtb")
        .arg("-o")
        .arg(&dtb_output_path)
        .arg(dts_source_path)
        .output()
        .expect("Failed to execute 'dtc'. Is device-tree-compiler installed on your system?");

    if !dtc_output.status.success() {
        panic!(
            "DTC Compilation Error: {}",
            String::from_utf8_lossy(&dtc_output.stderr)
        );
    }

    let dtb_data = std::fs::read(dtb_output_path).unwrap();
    // Parse Device Tree Binary file.
    let mut max_harts_cap: usize = 0;
    let mut paths: Vec<&str> = Vec::new();

    let mut guests: Vec<Guest> = Vec::new();
    let fdt = fdt::Fdt::new(&dtb_data).unwrap();
    if let Some(hypervisor) = fdt.find_node("/hypervisor-config") {
        for guest in hypervisor.children() {
            // Extract VM entry address.
            let entry = guest
                .property("entry")
                .expect("No entry field in DTS")
                .as_usize()
                .expect("Entry is not an integer");
            // Extract maximum number of harts for VM.
            let harts_cap = guest
                .property("harts-cap")
                .expect("No harts-cap field in DTS")
                .as_usize()
                .unwrap();

            let path = guest
                .property("path")
                .expect("No path field in DTS")
                .as_str()
                .unwrap();

            paths.push(path);

            // Find the maximum number of harts among all VMs.
            if harts_cap > max_harts_cap {
                max_harts_cap = harts_cap;
            }

            let guest = Guest::new(entry, harts_cap);

            guests.push(guest);
        }
    }

    // Create guests.rs file.
    let dest_path = std::path::Path::new(&out_dir).join("guests.rs");
    let mut f = std::fs::File::create(&dest_path).unwrap();

    writeln!(
        f,
        "
// Automaticly generated by build.rs. Do not edit. \n\
pub const MAX_HARTS_CAP: usize = {max_harts_cap};
pub static GUESTS: [Guest; {}] = [
        ",
        guests.len(),
    )
    .unwrap();

    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();

    for (i, guest) in guests.iter().enumerate() {
        writeln!(
            f,
            "
Guest {{
    entry_gpa: {},
    harts: core::sync::atomic::AtomicUsize::new(0),
    harts_cap: {},
    data: include_bytes!(\"{manifest_dir}/{}\"),
    vcpu: core::cell::UnsafeCell::new(crate::vcpu::Vcpu::zeroed()),
    vcpu_ptr: core::sync::atomic::AtomicPtr::new(core::ptr::null_mut()),
}},
            ",
            guest.entry_gpa, guest.harts_cap, paths[i]
        )
        .unwrap();
    }

    writeln!(f, "];").unwrap();
}
