[target.riscv64gc-unknown-none-elf]
rustflags = [
    "-C", "link-arg=-T",
    "-C", "link-arg=linker.ld",
    "-C", "target-feature=+v",
]
runner = "qemu-system-riscv64 -machine virt -cpu rv64,h=true,f=true,d=true,v=true,vlen=128,sstc=true -m 128M -smp 4 -serial mon:stdio -nographic -bios default -s -kernel"

[build]
target = "riscv64gc-unknown-none-elf"
